bar: {
    "height":30,
    "location":top,
    "background":141b23A9,
    "layer":bottom,
    "font":NotoSansArabic-20,
    "foreground":FFFFFFFF,
    "margin":2,
    "right":[
        {
            "pulse":{
                "content":{
                    "map":{
                        "conditions":{
                            "(sink_muted)":{
                                "progress-bar":{
                                    "tag":"0",
                                    "length":10,
                                    "start":{"string":{"text":"\u25FC"}},
                                    "end":{"string":{"text":""}},
                                    "fill":{"string":{"text":"\u25B0"}},
                                    "empty":{"string":{"text":"\u25B1"}},
                                    "indicator":{"string":{"text":""}}
                                }
                            },
                            "~(sink_muted)":{
                                "progress-bar":{
                                    "tag":"sink_percent",
                                    "length":10,
                                    "start":{"string":{"text":""}},
                                    "end":{"string":{"text":""}},
                                    "fill":{"string":{"text":"\u25B0"}},
                                    "empty":{"string":{"text":"\u25B1"}},
                                    "indicator":{"string":{"text":""}}
                                }
                            }
                        }
                    }
                }
            }
        }
    ],

    "left":[
        {
            "i3":{
                "persistent":["1","2","3","4","5"],
                "spacing":2,
                "content":{
                    "":{
                        "map":{
                            "conditions":{
                                    "(focused)":{"string":{"text":"\u25B0","foreground":FFFFFFFF}},
                                    "(~focused)":{"string":{"text":"\u25B1","foreground":FFFFFFFF}},
                                }
                            }
                        }
                    }
                }
        }
    ],

    "center":[
        {
            "clock":{
                "content":{
                    "string":{
                        "text":"{time}",
                        "font":"NotoSansArabic-25",
                    }
                }
            }
        }
    ]
}
