bar: {
    "height":44,
    "location":top,
    "background":141b23A9,
    "layer":bottom,
    "font":JetBrainsMonoNerdFont-36,
    "foreground":FFFFFFFF,
    "margin":2,
    "right":[
        {
            "battery":{
                "name":"BAT0",
                "content":{
                    "map":{
                        "conditions":{
                            "(capacity<=10)":{
                                "string":{
                                    "foreground":FF0000FF,
                                    "text":"󰪞",
                                }
                            },
                            "(capacity>10)&&(capacity<=20)":{
                                "string":{
                                    "foreground":FFFF00FF,
                                    "text":"󰪟",
                                }
                            },
                            "(capacity>20)&&(capacity<=40)":{
                                "string":{
                                    "text":"󰪠",
                                }
                            },
                            "(capacity>40)&&(capacity<=60)":{
                                "string":{
                                    "text":"󰪡",
                                }
                            },
                            "(capacity>60)&&(capacity<=70)":{
                                "string":{
                                    "text":"󰪢",
                                }
                            },
                            "(capacity>70)&&(capacity<=80)":{
                                "string":{
                                    "text":"󰪣",
                                }
                            },
                            "(capacity>80)&&(capacity<=90)":{
                                "string":{
                                    "text":"󰪤",
                                }
                            },
                            "(capacity>90)&&(capacity<=100)":{
                                "string":{
                                    "text":"󰪥",
                                }
                            }
                        }
                    }
                }
            }
        },
        {
            "label": {
                "content":{
                    "string":{
                        "text":" ",
                    } 
                }
            } 
        },
        {
            "pulse":{
                "content":{
                    "map":{
                        "conditions":{
                            "(sink_muted)":{
                                "progress-bar":{
                                    "tag":"0",
                                    "length":10,
                                    "start":{"string":{"text":"\u25FC"}},
                                    "end":{"string":{"text":""}},
                                    "fill":{"string":{"text":"\u25B0"}},
                                    "empty":{"string":{"text":"\u25B1"}},
                                    "indicator":{"string":{"text":""}}
                                }
                            },
                            "~(sink_muted)":{
                                "progress-bar":{
                                    "tag":"sink_percent",
                                    "length":10,
                                    "start":{"string":{"text":""}},
                                    "end":{"string":{"text":""}},
                                    "fill":{"string":{"text":"\u25B0"}},
                                    "empty":{"string":{"text":"\u25B1"}},
                                    "indicator":{"string":{"text":""}}
                                }
                            }
                        }
                    }
                }
            }
        }
    ],

    "left":[
        {
            "i3":{
                "persistent":["1","2","3","4","5"],
                "spacing":2,
                "content":{
                    "":{
                        "map":{
                            "conditions":{
                                    "(focused)":{"string":{"text":"\u25B0","foreground":FFFFFFFF}},
                                    "(~focused)":{"string":{"text":"\u25B1","foreground":FFFFFFFF}},
                                }
                            }
                        }
                    }
                }
        }
    ],

    "center":[
        {
            "clock":{
                "content":{
                    "string":{
                        "text":"{time}",
                        "font":"JetBrainsMonoNerdFont-37",
                    }
                }
            }
        }
    ]
}
